apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  selector:
    matchLabels:
      app: mongo-db
  replicas: 1
  # strategy:
  #  type: Recreate
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongodb-container
        image: anantya/mongodb-test
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "pass"

        - name: MONGO_INITDB_DATABASE
          value: "animal_db"
   
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-lb
spec:
  selector:
    app: mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017